name: node-app-5-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Declare some variables
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses:  docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: arjun150800/node-app-5:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      -
        uses: actions/checkout@v3
      # -
      #   name: Modify values file
      #   shell: bash
      #   run: |
      #     echo ${{needs.ci.outputs.commit_id}}
      #     pipx install yq
      #     export PATH="$HOME/.local/bin:$PATH"
      #     yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/node-app-5/values-dev.yaml
      -
        name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

      -
        name: Deploy using Helm
        shell: bash
        run: |
          helm upgrade --install \
            node-app-5 charts/node-app-5 \
            --set image.tag=${{needs.ci.outputs.commit_id}} \
            --namespace dev \
            --create-namespace \
            -f charts/node-app-5/values-dev.yaml